### ISSUE TITLE
Auto fire not working

### ISSUE THREAD

**Issue by CatKreamer** [billyotheokid/KGB#2]
Basically the auto-fire is stop working after your update a while ago.
KGB forever,
{Death} Jesus

**Comment by billyotheokid** [comment]
try re-downloading

**Comment by billyotheokid** [comment]
oh wait 1 sec i see the issue

**Comment by billyotheokid** [comment]
its fixed redownload

**Comment by billyotheokid** [comment]
Fixed as of 7/3/2023.  closing
